/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nobu' at '17/06/18 9:15' with Gradle 2.14.1
 *
 * @author nobu, @date 17/06/18 9:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
